---
title: Testing functions
format:
  html:
    embed-resources: true
---

```{r}
data_dir <- "../../workbench/data/one_hot"
config_path <- "../../workbench/config.csv"

source("config.R")
source("potential.R")
source("raster.R")

# Load global config
config <- load_config()

head(config)
```

## Generate alphabetically-ordered config

```r
config <- config[order(config[["Name"]]), ]

readr::write_csv(config, "_config.csv")
```


```r
rownames(config) <- config[["Name"]]

config[["Name"]] <- NULL
config[["Dataset"]] <- NULL
config[["Raster_Val"]] <- NULL
config[["Component"]] <- NULL

# Sort alphabetically for sanity
config <- config[order(rownames(config)), , drop = FALSE]

print(config)

readr::write_csv(config, "reference.csv")
```

## Generate reference persona

```r
config <- load_config()

persona <- data.frame(
  random = sample(0:10, size=87, replace = TRUE)
)
rownames(persona) <- config[["Name"]]
  
head(persona)

save_persona(persona, "test_persona.csv")
```

## Test saving and loading a new persona file

```{r}
config <- load_config()
persona <- setNames(
    sample(0:10, size = 87, replace = TRUE),
    config[["Name"]]
)
persona

file.remove("test_persona.csv")

save_persona(persona, "test_persona.csv", "random")

loaded_persona <- load_persona("test_persona.csv")

identical(persona, loaded_persona)
```


```r
persona2 <- setNames(
    sample(0:10, size = 87, replace = TRUE),
    config[["Name"]]
)

save_persona(persona2, "test_persona.csv", "random2")
save_persona(persona2, "test_persona.csv", "random2")

loaded_persona <- load_persona("test_persona.csv", "random2")

loaded_persona

# file.remove("test_persona.csv")
```

## Test RP

```{r}
persona <- load_persona("test_persona.csv")
data_dir <- "../../workbench/data/one_hot/"

layers <- compute_potential(persona, data_dir)

terra::plot(layers)
```
