# Stage 3 (distance)

```{r include=FALSE}
library(dplyr)
library(terra)

devtools::load_all("../model")
source("production.R")

config <- load_config()
feature_mappings <- get_feature_mappings(config)


bush <- vect("data/Shapefiles/Bush/Bush.shp")
cairngorms <- vect("data/Legacy/Legacy_Data/input/Raw_Shapefile/CairngormNP/CairngormNP.shp")
stirlingshire <- vect("data/Legacy/Legacy_Data/input/Raw_Shapefile/Stirlingshire/Stirlingshire.shp")
scotland <- vect("data/Scotland/boundaries.shp")
```

## Check things makes sense

```{r}
rast("data/Stage_2/FIPS_I.tif") |> crop(bush) |> plot(col = c("black", "red"))
```

```{r}
stage_3_files <- get_files("data/Stage_3")
stage_3_files

#stage_3_files[["FIPS_I_buf"]] |> rast() |> plot()

stage_3_files[["FIPS_I_dist"]] |> rast() |> plot()

stage_3_files[["FIPS_I"]] |> rast() |> plot()
```

## Using focal

```r
files <- get_files("data/Stage_3b")
files

files[["FIPS_I_buf"]] |> rast() |> plot()
files[["FIPS_I_dist"]] |> rast() |> plot()
files[["FIPS_I"]] |> rast() |> plot()

files[["Water_buf"]] |> rast() |> plot()
files[["Water_dist"]] |> rast() |> plot()
files[["Water"]] |> rast() |> plot()
```

## Gauss

```r
files <- get_files("data/Test_Stage_3")
files

files[["FIPS_I"]] |> rast() |> plot()

files[["Water"]] |> rast() |> plot()
```
