about_html <- tags$div(
    tags$h2("About"),
    "The Recreational Potential value is made up of 87", tags$em("items"), "representing distinct attributes of the land.",
    "The 87 items are grouped into four", tags$em("components"), "which are accessed through the tabs alongside the 'About' tab.",
    tags$p(),
    tags$ul(
        tags$li(tags$strong("SLSRA:"), "Suitability of Land to Support Recreational Activity"),
        tags$li(tags$strong("FIPS_N:"), "Natural Features Influencing the Potential Provision"),
        tags$li(tags$strong("FIPS_I:"), "Infrastructure Features Influencing the Potential Provision"),
        tags$li(tags$strong("Water:"), "Rivers and lakes")
    ),
    "The Recreational Potential value is calculated by weighting each item by a", tags$em("score"), "that reflects the importance of that item to the user.",
    "A full set of 87 scores is referred to as a", tags$em("persona."),
    tags$p(),
    "Each 20x20 metre square of land within the chosen area is given a Recreational Potential value between zero and one, with higher values indicating greater Recreational Potential.",
    "Note that a value of one (zero) represents the highest (lowest) Recreational Potential", tags$em("within the chosen area."), "and not the highest (lowest) value anywhere in Scotland.",
    tags$p(),
    tags$h3("How to use this tool"),
    "You will need to decide on a score, between 0 (of no importance) and 10 (of the highest importance), for each of the 87 items, according to the value of that item from your personal perspective.",
    # "If, from the viewpoint of your persona, you do not feel that an item is relevant to the recreational potential, you should give it a score of 0.",
    tags$p(),
    "Each user is expected to create multiple personas, aligned to different recreational objectives (e.g. running alone versus walking with one's family).",
    tags$p(),
    "A good place to start is by loading either the 'Hard Recreationalist' or 'Soft Recreationalist' persona and editing the scores as appropriate.",
    "You can load a persona by clicking the 'Load Persona' button.",
    "In the pop-up dialogue, you should select 'examples' as the user.",
    tags$p(),
    "Once you are happy with your persona scores, the next step is to choose an area to compute the Recreational Potential.",
    "Click on the red box on the map, and drag your mouse across the map to select an area.",
    tags$p(),
    "You are now ready to click the 'Update Map' button.",
    "Once it has been calculated, the Recreational Potential value will be overlayed as a 'heatmap' on top of the map of Scotland to your right.",
    "You can also view individual heatmaps for the four components.",
    tags$p(),
    "Since creating a persona takes a fair amount of effort, you can save personas for loading again in the future.",
    "To do so, click the 'Save Persona' button.",
    "If this is your first persona, enter a", tags$em("unique"), "user name.",
    "Otherwise, you can select your user name from the dropdown menu.",
    "Then enter a", tags$em("unique"), "name for the persona in the dialogue, and click 'Save'.",
    tags$p(),
    "Finally, note that you can view, load and, if you're not careful,", tags$em("overwrite"), "other users' personas.",
    "Please be responsible!",
    tags$p(),
    tags$h3("Further information"),
    "This Recreational Potential tool for Scotland was developed by the", tags$a(href = "https://www.ceh.ac.uk", "UK Centre for Ecology & Hydrology", target = "_blank"), "as part of the", tags$a(href = "https://biodt.eu/", "BioDT Prototype Digital Twins", target = "_blank"), "project.",
    tags$p(),
    "Information about how we process your data can be found in our ", tags$a(href = "https://www.ceh.ac.uk/privacy-notice", "privacy notice.", target = "_blank"),
    "For further information, please contact Dr Jan Dick (jand@ceh.ac.uk)."
)
