about_html <- tags$div(
    tags$h2("About"),
    "Each 20x20 metre square of land is given a Recreational Potential value between zero and one, with higher values representing Recreational Potential.",
    "These values will be calculated and then overlayed as a 'heatmap' on top of the map of Scotland to your right.",
    tags$p(),
    "The Recreational Potential value is made up of 87", tags$em("items"), "representing distinct attributes of the land [MORE NEEDED].",
    "The 87 items are grouped into four", tags$em("components"), "which are accessed through the tabs alongside the 'About' tab.",
    tags$p(),
    tags$ul(
        tags$li(tags$strong("SLSRA:"), "Suitability of Land to Support Recreational Activity"),
        tags$li(tags$strong("FIPS_N:"), "Natural Features Influencing the Potential Provision"),
        tags$li(tags$strong("FIPS_I:"), "Infrastructure Features Influencing the Potential Provision"),
        tags$li(tags$strong("Water:"), "Water Elements")
    ),
    "The Recreational Potential value is calculated by weighting each item by a", tags$em("score"), "that reflects the importance of that item to the user.",
    "A full set of 87 scores is referred to as a", tags$em("persona."),
    tags$p(),
    tags$h3("How to use this tool"),
    "You will need to decide on a score, between 0 (of no importance) and 10 (of the highest importance), for each of the 87 items, according to the value of that item from your personal perspective.",
    # "If, from the viewpoint of your persona, you do not feel that an item is relevant to the recreational potential, you should give it a score of 0.",
    tags$p(),
    "Each user is expected to create multiple personas, aligned to different recreational objectives (e.g. running alone versus walking with one's family).",
    "Personas can be saved and re-loaded using the 'Load Persona' and 'Save Persona' buttons.",
    tags$p(),
    "A good place to start is by loading either the 'Hard Recreationalist' or 'Soft Recreationalist' persona from 'examples.csv', and editing the scores as appropriate.",
    tags$p(),
    "Once you are happy with your persona scores, click the 'Update Map' button to view heatmaps for each of the four components, as well as the full Recreational Potential value.",
    tags$p(),
    tags$h3("Further information"),
    "This Recreational Potential tool for Scotland was developed by the", tags$a(href = "https://www.ceh.ac.uk", "UK Centre for Ecology & Hydrology", target = "_blank"), "as part of the", tags$a(href = "https://biodt.eu/", "BioDT Prototype Digital Twins", target = "_blank"), "project.",
    tags$p(),
    "Information about how we process your data can be found in our ", tags$a(href = "https://www.ceh.ac.uk/privacy-notice", "privacy notice.", target = "_blank"),
    "For further information, please contact Dr Jan Dick (jand@ceh.ac.uk)."
)
